import Head from 'next/head'
import { Supplier } from '@/types'
import SupplierTable from '@/components/SupplierTable'
import { useEffect, useState } from 'react'
import EditSupplier from '../components/EditSupplier';
import { isValidSupplier } from '@/lib/supplier.validator';
import FlashMessage from '../components/FlashMessage';

export default function  Home() {  
  
  const [supplierList, setSuppliersList] : [Array<Supplier>|undefined, Function] = useState();
  const [dirtySupplier, setDirtySupplier]: [Partial<Supplier>|undefined, Function] = useState();
  const [activeSupplier, setActiveSupplier]: [Partial<Supplier>|undefined, Function] = useState();
  const [flashMessage, setFlashMessage]: [string, Function] = useState('')

  //fetching initial data
  useEffect(()=>{
    async function fetchData() {
      const res = await fetch('http://localhost:8080/api/suppliers')
      if (!res.ok) {
        throw new Error('Failed to fetch data')
      }
      const responsedData = await res.json();
      setSuppliersList(responsedData)
    }
    //setTimeout(fetchData, 3000)
    fetchData()
  }, [])

  // creating and updating suppliers
  useEffect(()=>{
    if (!dirtySupplier) { return }

    let fetchUrl = 'http://localhost:8080/api/suppliers'
    let fetchMethod = 'POST'

    if (dirtySupplier.id) {
      // this one already exists and we need to update
      fetchMethod = 'PUT'
      fetchUrl = `http://localhost:8080/api/suppliers/${dirtySupplier.id}`
    } 

    async function createOrUpdateSupplier() {
      const res = await fetch(fetchUrl, 
        { 
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
          },
          method:fetchMethod,
          body: JSON.stringify(dirtySupplier)
        })
      
      if (!res.ok) {
        throw new Error('Failed to fetch data')
      }

      const responsedData = await res.json();
      if (responsedData.message) {
        setFlashMessage( `${responsedData.message}`)
        return 
      }
      // create a clone so that a state change won't act weird
      // let newSuppliersList = [ ...supplierList || [] ]
      let updateIdx:number = -1;
      if (supplierList) {
        updateIdx = supplierList.findIndex( supplier => ( supplier.id === responsedData.id ))
        if ( updateIdx >= 0 ) {
          supplierList.splice(updateIdx, 1, responsedData)
        } else {
          supplierList.push(responsedData)
        }
      }
      
      setSuppliersList( [ ... supplierList || [responsedData] ])
      setFlashMessage( `Supplier ${responsedData.name} has been ${ updateIdx? 'updated' : 'saved'}.`)
      setDirtySupplier(null); 
      setActiveSupplier(null); 
    }
    createOrUpdateSupplier()

  }, [dirtySupplier])

  // dismiss flash message after 15 seconds
  useEffect(()=>{
    setTimeout( () =>{
      setFlashMessage('')
    }, 15000)
  }, [flashMessage])
  
  function handleSupplierChange(payload:Partial<Supplier>) {
    if (isValidSupplier(payload)) {
      setDirtySupplier(payload); 
    }
  }

  function handleAddNew() {
    setActiveSupplier({})
  }

  function handleCancelEdit(){
    setActiveSupplier(null)
  }

  function handleInsepctRequest(supplier:Supplier){
    setActiveSupplier(supplier)
  }

  function handleSupplierDeleteRequest(supplier:Supplier){
    async function deleteSupplier() {
      const res = await fetch(`http://localhost:8080/api/suppliers/${supplier.id}`, 
        { 
          method: "DELETE"
        })
      if (!res.ok) {
        throw new Error('Failed to delete data')
      }

      if (supplierList) {
        const itemIdx: number = supplierList.indexOf(supplier);
        supplierList.splice(itemIdx, 1)
        setSuppliersList([...supplierList])
      }
      
      setFlashMessage( `Supplier ${supplier.name} has been deleted.`)

    }
    deleteSupplier()
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="relative pt-[4rem] max-w-screen-sm mx-auto">
        <div className={ activeSupplier ? "blur" : "" }>
          <div className="flex py-[1rem] mb-[2rem] border-b-4 border-ui">
            <h1 className="grow text-2xl font-bold">Suppliers </h1>
            <button onClick={handleAddNew} className="btn">Add Supplier</button>
          </div>
          { !supplierList 
            ? <>Fetching Supplier List</>
            : <SupplierTable suppliers={supplierList} onDeleteRequest={handleSupplierDeleteRequest} onInspectRequest={handleInsepctRequest} />
          }
        </div>
        { activeSupplier
          ? <div className="absolute bg-light2 max-w-[400px] m-auto top-[4rem] left-0 right-0 p-[2rem] border-4 border-ui" >
              <EditSupplier supplier={ activeSupplier || {} } onChange={handleSupplierChange} onCancel={handleCancelEdit} />
            </div>
          : <></>
        }
          <div className={`absolute top-0 left-0 right-0 text-sm border border-uiLight bg-alertLight p-[1rem] ${flashMessage ? 'block' : 'hidden'}`}>
          { flashMessage }
          </div>
      </main>
    </>
  )
}
